### ISSUE TITLE
Insights for a possible super black, higher-contrast and vibrant variant

### ISSUE THREAD

**Issue by oakromulo** [tinacious/vscode-tinacious-design-syntax#18]
Hi! I don't know if I'm contributing in any way (feel free to just close the issue) but these are the overrides under `settings.json` that I use over the high-contrast theme. It seems to be quite a hit among my co-workers too:
```
"workbench.colorCustomizations": {
  "[Tinacious Design (High Contrast) (2016)]": {
    "editorRuler.foreground": "#aaaaaa33",
    "editor.background": "#000000",
    "sideBar.background": "#090909cc",
    "activityBar.background": "#050505",
    "statusBar.background": "#050505",
    "titleBar.activeBackground": "#050505",
    "titleBar.activeForeground": "#ffffff",
    "input.background": "#141414",
    "tab.inactiveBackground": "#151515",
    "tab.activeBorder": "#000000",
    "tab.border": "#000000",
    "editorGroupHeader.tabsBackground": "#000000",
    "editor.selectionBackground": "#aaaaaa44",
    "scrollbarSlider.background": "#555555aa",
    "editorWhitespace.foreground": "#303030aa",
    "tree.indentGuidesStroke": "#00000000",
    "editorCursor.foreground": "#ff5722"
  }
},
"workbench.colorTheme": "Tinacious Design (High Contrast) (2016)",
"editor.tokenColorCustomizations": {
  "[Tinacious Design (High Contrast) (2016)]": {
    "comments": "#888888"
  }
}
```

**Comment by tinacious** [comment]
Thanks for your contribution! Can you please provide a screenshot? I'd like to take a look before I suggest creating a PR. Thank you! 🙏

**Comment by oakromulo** [comment]
Sure thing @tinacious - idiot me forgot the obvious, sorry!
![Screen Shot 2020-12-07 at 19 36 35](https://user-images.githubusercontent.com/19331468/101384817-9ab0fa80-38c3-11eb-9104-9eb13fd068a9.png)

**Comment by oakromulo** [comment]
<img width="1263" alt="Screen Shot 2020-12-07 at 19 39 11" src="https://user-images.githubusercontent.com/19331468/101385049-ebc0ee80-38c3-11eb-89c3-f600c7777a59.png">

**Comment by oakromulo** [comment]
p.s. the color definitely need some rounding/truncation to get closer to your palette and design language - just pointing a direction that seems to be well-liked but high-contrast devs
