### ISSUE TITLE
Some highlight problems in HTML file.

### ISSUE THREAD

**Issue by hzz888** [tinacious/vscode-tinacious-design-syntax#22]
Some tags are highlighted normally, but some not.
![image](https://user-images.githubusercontent.com/60465723/104121484-958b1380-5379-11eb-9848-c02eb3296e1a.png)

**Comment by tinacious** [comment]
Thanks for the report! Will look into it.

**Comment by hzz888** [comment]
Hello! I found just now that the issue doesn't matter at all . I think the "align" and "border" were not highlighted because they are not standard HTML tags, they have been abandoned, they should be used in CSS file. So I don't think it is a problem. Sorry for disturbing.

**Comment by tinacious** [comment]
Thanks for clarifying @hzz888. Will close but feel free to re-open if it's no longer the case.

**Comment by hzz888** [comment]
You're welcome!
