### ISSUE TITLE
Restore support for older 2017 themes

### ISSUE THREAD

**Issue by sunmaer** [tinacious/vscode-tinacious-design-syntax#8]
The new color combination is dazzling，is there a way to use the previous version?

**Comment by tinacious** [comment]
Yes! I'll add support to restore the old ones. Stay tuned. ⏳

**Comment by tinacious** [comment]
Done! The changes should propagate shortly if they haven't already. See the linked PR for details.

🚢 :shipit: 🚀

**Comment by sunmaer** [comment]
> Yes! I'll add support to restore the old ones. Stay tuned. ⏳

Great, thank you very much!
